### ISSUE TITLE
Error in estimate_cell_cycle_transitions.py (and a minor one in DeepCycle.py)

### ISSUE THREAD

**Issue by jtheorell** [andreariba/DeepCycle#11]
Dear @andreariba, 
I find this concept very appealing, and I am currently trying to implement it for my SmartSeq2 data. I am an R person, and very unused to python, so my issues are probably easy to solve, but I would need some extra help anyway. With my own data, I managed to get DeepCycle.py to work, once I changed: 

sns.scatterplot(np_data[:,2*index],np_data[:,2*index+1],alpha=0.1,ax=ax)
sns.kdeplot(np_data[:,2*index],np_data[:,2*index+1],shade=False,cmap="Reds",ax=ax)

to 

sns.scatterplot(x = np_data[:,2*index], y = np_data[:,2*index+1],alpha=0.1,ax=ax)
sns.kdeplot(x = np_data[:,2*index], y = np_data[:,2*index+1],shade=False,cmap="Reds",ax=ax)

on rows 586-587. However, when I try to run estimate_cell_cycle_transitions.py, it does not work. When I try to run it with your velocity_anndata_human_fibroblast_DeepCycle_ISMARA.h5ad dataset and the command: 

python3 Scripts/estimate_cell_cycle_transitions.py \
  --input_adata velocity_anndata_human_fibroblast_DeepCycle_ISMARA.h5ad \
  --gene_phase_dict ./theta_annotation/gene_phase_dict.json \
  --output_npy_transitions ./theta_transitions_fibro.npy \
  --output_svg_plot ./cell_cycle_phase_detection_fibro.svg

 I get the following error message (which is more or less identical to the one I get for my data):

Traceback (most recent call last):
  File "/Users/jakob.theorell/OneDrive - Karolinska Institutet/Mac/Desktop/DeepCycle/Scripts/estimate_cell_cycle_transitions.py", line 192, in <module>
    add_cell_cycle_scores(adata, gene_phase_dict)
  File "/Users/jakob.theorell/OneDrive - Karolinska Institutet/Mac/Desktop/DeepCycle/Scripts/estimate_cell_cycle_transitions.py", line 53, in add_cell_cycle_scores
    G1S_total = np.append(G1S_total, scipy.stats.zscore(adata[:,gene].layers['Ms']))
  File "/Users/jakob.theorell/Library/Python/3.10/lib/python/site-packages/scipy/stats/_stats_py.py", line 2730, in zscore
    return zmap(a, a, axis=axis, ddof=ddof, nan_policy=nan_policy)
  File "/Users/jakob.theorell/Library/Python/3.10/lib/python/site-packages/scipy/stats/_stats_py.py", line 2896, in zmap
    std[isconst] = 1.0
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anndata/_core/views.py", line 35, in __setitem__
    container[idx] = value
IndexError: boolean index did not match indexed array along dimension 0; dimension is 5367 but corresponding boolean dimension is 1

Please could you provide an explanation and a solution to this? Thank you very much in advance. 
Best regards
Jakob

**Comment by andreariba** [comment]
Hi Jakob,

unfortunately I don't have a way to test it because I quitted academia and I don't have access to the computational resources  necessary to run DeepCycle anymore. 

Did you use the conda environment in the repository?

**Comment by jtheorell** [comment]
Dear Andrea, 
Thank you so much for this quick reply! I did not manage to make the conda environment work actually, but I got DeepCycle to work nicely (I have a very workable dataset of 500 cells, so I could do it locally), and this new issue seems to me more like a formatting issue to me. But it sounds like you have not seen this issue before for that script then? And further: is there any way of interpreting the theta values in a more approximate way, without estimating the transitions with the script? In other words: I might not need to run this latter script if I can convincingly show that a considerable portion of my cells are in active cell division.

**Comment by andreariba** [comment]
your issue looks like related to the scipy version you're using but unfortunately I've never seen that particular error.

You can perhaps try to show the expression of cycling genes (cyclins, ...) in function of theta and see if they are effectively cycling. Choosing the right genes will allow you to have a rough estimation of the phases.
Then you could make a dimensionality reduction map (like umap) and color the cells by theta.

I found that the strategy I followed in the paper was quite effective, but be aware that if you have many non cycling cells, DeepCycle won't work. To make it run on the fibroblast dataset, I prefiltered the cells in the quiescent state based on clustering of the expression data and quiescence markers.

Let me know if I can help you more

**Comment by macrinalobo** [comment]
@jtheorell  I had the same issue. Changing to G1S_total = np.append(G1S_total, scipy.stats.zscore(np.array(adata[:,gene].layers['Ms']))) fixed it for me. scipy.stats.zscore was used in 2 other places in that file where I did the same thing.

**Comment by jtheorell** [comment]
Great, thank you, @macrinalobo!
