### ISSUE TITLE
Issue with Anndata

### ISSUE THREAD

**Issue by JDBLab** [andreariba/DeepCycle#14]
Dear @andreariba, 

Thank you so much for developing the DeepCycle package. It's really good. I ran the code on the example file- velocity_anndata_human_fibroblast_DeepCycle_ISMARA.h5ad and it worked smoothly. However, when I tried to run on my data it's giving me the following error-

(DeepCycle) mayurd@mayurdlaptop:~/Downloads/DeepCycle-main_new/DeepCycle-main$ python DeepCycle1.py   --input_adata MD_Newanalysis.h5ad   --gene_list go_annotation/GO_cell_cycle_annotation_human.txt   --base_gene MELK   --expression_threshold 0   --output_adata adata_newbeta1_DeepCycle.h5ad
[Current working directory]: /home/mayurd/Downloads/DeepCycle-main_new/DeepCycle-main
[TensorFlow version]: 2.2.0
[Loading anndata]: Traceback (most recent call last):
  File "/home/mayurd/miniconda3/envs/DeepCycle/lib/python3.7/site-packages/anndata/_io/utils.py", line 156, in func_wrapper
    return func(elem, *args, **kwargs)
  File "/home/mayurd/miniconda3/envs/DeepCycle/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 510, in read_group
    EncodingVersions[encoding_type].check(
  File "/home/mayurd/miniconda3/envs/DeepCycle/lib/python3.7/enum.py", line 357, in __getitem__
    return cls._member_map_[name]
KeyError: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepCycle1.py", line 263, in <module>
    adata = anndata.read_h5ad(input_adata_file)
  File "/home/mayurd/miniconda3/envs/DeepCycle/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 413, in read_h5ad
    d[k] = read_attribute(f[k])
  File "/home/mayurd/miniconda3/envs/DeepCycle/lib/python3.7/functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/mayurd/miniconda3/envs/DeepCycle/lib/python3.7/site-packages/anndata/_io/utils.py", line 163, in func_wrapper
    f"Above error raised while reading key {elem.name!r} of "
anndata._io.utils.AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.

I have analyzed raw scRNAseq data with Seurat and created seuratobject which I then exported as metadata, counts file in .mtx format, pca and gene names files. Further, I used scanpy code to create anndata
file. The anndata file was preprocessed to run pp.moments from scVelo to generate imputed unspliced (Mu) and spliced (Ms) expressions. I have attached the structure of my anndata in comparison with example file which I used. Could you please guide me in resolving this error? Thank you in advance. 

![image](https://user-images.githubusercontent.com/50833242/225405435-7f59c4b4-909b-40af-b629-489229d2e1b4.png)

**Comment by andreariba** [comment]
I really cannot help without more details, I suppose you're using the wrong version of Anndata or perhaps you save it with a older/newer version. The issue anyway it's related with anndata not with DeepCycle.

**Comment by nroak** [comment]
I have a similar issue with anndata that was created by Scanpy-

```
(DeepCycle) [noak@noderome102 deepCycle]$ python ~/resources/DeepCycle/DeepCycle.py \
>   --input_adata ../adata_harmony.clustered.annotated.velocity.h5ad \
>   --gene_list ~/resources/DeepCycle/go_annotation/GO_cell_cycle_annotation_mouse.txt \
>   --base_gene Nusap1 \
>   --expression_threshold 0.5 \
>   --hotelling \
>   --output_adata adata_harmony.clustered.annotated.velocity.DeepCycle.h5ad
[Current working directory]: scanpy/deepCycle
[TensorFlow version]: 2.2.0
[Loading anndata]: Traceback (most recent call last):
  File "/home/noak/.conda/envs/DeepCycle/lib/python3.7/site-packages/anndata/_io/utils.py", line 156, in func_wrapper
    return func(elem, *args, **kwargs)
  File "/home/noak/.conda/envs/DeepCycle/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 510, in read_group
    EncodingVersions[encoding_type].check(
  File "/home/noak/.conda/envs/DeepCycle/lib/python3.7/enum.py", line 357, in __getitem__
    return cls._member_map_[name]
KeyError: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/noak/resources/DeepCycle/DeepCycle.py", line 263, in <module>
    adata = anndata.read_h5ad(input_adata_file)
  File "/home/noak/.conda/envs/DeepCycle/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 413, in read_h5ad
    d[k] = read_attribute(f[k])
  File "/home/noak/.conda/envs/DeepCycle/lib/python3.7/functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/noak/.conda/envs/DeepCycle/lib/python3.7/site-packages/anndata/_io/utils.py", line 163, in func_wrapper
    f"Above error raised while reading key {elem.name!r} of "
anndata._io.utils.AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.
```

**Comment by TangentDeng** [comment]
Same issue. Any way to solve this?

**Comment by TangentDeng** [comment]
Update the anndata to 0.8.0 fix it

**Comment by MadeleineDale** [comment]
@Roger-GOAT do you mind sharing your .yml file with the updated environment if you still have it? My conda/mamba is not able to resolve the conflicts created by trying to update anndata to this version. It would be much appreciated :)

**Comment by MadeleineDale** [comment]
Using pip instead to update the environment created with conda from the original yml file, I was able to get a working environment, that I give below:
 
name: DeepCycle
channels:
  - glotzer
  - defaults
  - bioconda
  - conda-forge
  - r
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - argon2-cffi=20.1.0=py37h7b6447c_1
  - astunparse=1.6.3=py_0
  - attrs=20.1.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=py_0
  - blinker=1.4=py37_0
  - brotlipy=0.7.0=py37h7b6447c_1000
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2024.9.24=h06a4308_0
  - cachetools=4.1.1=py_0
  - cairo=1.14.12=h8948797_3
  - certifi=2022.12.7=py37h06a4308_0
  - cffi=1.14.2=py37he30daa8_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - cloudpickle=1.6.0=py_0
  - cryptography=3.1=py37h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py37_0
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - dill=0.3.2=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.9=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - future=0.18.2=py37_1
  - gast=0.3.3=py_0
  - gettext=0.19.8.1=h9b4dc7a_1
  - glib=2.65.0=h3eb4bd4_0
  - google-auth=1.21.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - googleapis-common-protos=1.51.0=py37_2
  - graphite2=1.3.14=h23475e2_0
  - graphviz=2.38.0=hcf1ce16_1009
  - grpcio=1.31.0=py37hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.18.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.17.2=py37_0
  - jinja2=2.11.2=py_0
  - joblib=1.0.0=pyhd3eb1b0_0
  - jpeg=9d=h516909a_0
  - jsonschema=3.2.0=py37_1
  - jupyter_client=6.1.6=py_0
  - jupyter_core=4.6.3=py37_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py37hfd86e86_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.13.0=hd408876_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libtool=2.4.6=h7b6447c_5
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - llvmlite=0.34.0=py37h269e1b5_4
  - lz4-c=1.9.2=he6710b0_1
  - markdown=3.2.2=py37_0
  - markupsafe=1.1.1=py37h14c3975_1
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py37h817c723_0
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - natsort=7.0.1=py_0
  - nbconvert=5.6.1=py37_1
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - notebook=6.1.1=py37_0
  - numba=0.51.2=py37h04863e7_1
  - numpy=1.19.1=py37hbc911f0_0
  - numpy-base=1.19.1=py37hfa32c7d_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py37_0
  - openssl=1.1.1w=h7f8727e_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.4=py_0
  - pandas=1.1.1=py37he6710b0_0
  - pandoc=2.10.1=0
  - pandocfilters=1.4.2=py37_1
  - pango=1.40.14=he752989_2
  - parso=0.7.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py37_1
  - pickleshare=0.7.5=py37_1001
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.2.2=py37_0
  - pixman=0.40.0=h7b6447c_0
  - prometheus_client=0.8.0=py_0
  - promise=2.3=py37_0
  - prompt-toolkit=3.0.7=py_0
  - protobuf=3.13.0=py37hf484d3e_0
  - psutil=5.7.2=py37h7b6447c_0
  - ptyprocess=0.6.0=py37_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_2
  - pydot=1.3.0=py37_0
  - pygments=2.6.1=py_0
  - pyjwt=1.7.1=py37_0
  - pynndescent=0.5.1=pyhd3deb0d_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.16.0=py37h7b6447c_0
  - pysocks=1.7.1=py37_1
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - pyzmq=19.0.1=py37he6710b0_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.6=py_0
  - scikit-learn=0.23.2=py37h0573a6f_0
  - seaborn=0.10.1=py_0
  - send2trash=1.5.0=py37_0
  - setuptools=49.6.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tbb=2020.3=hfd86e86_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow-datasets=1.2.0=py37_0
  - tensorflow-gpu=2.2.0=h0d30ee6_0
  - tensorflow-metadata=0.14.0=pyhe6710b0_1
  - tensorflow-probability=0.7=py_2
  - termcolor=1.1.0=py37_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.48.2=py_0
  - traitlets=4.3.3=py37_0
  - umap-learn=0.5.0=py37h89c1867_0
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=py_0
  - wrapt=1.12.1=py37h7b6447c_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.2=h470a237_5
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.2=he6710b0_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
      - absl-py==2.1.0
      - anndata==0.8.0
      - cached-property==1.5.2
      - celluloid==0.2.0
      - flatbuffers==24.3.25
      - h5py==3.3.0
      - keras==2.11.0
      - libclang==18.1.1
      - scipy==1.4.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - typing-extensions==4.7.1
