### ISSUE TITLE
How many cycle genes should be calculated at least?

### ISSUE THREAD

**Issue by TangentDeng** [andreariba/DeepCycle#17]
[Genes]: ['Actb', 'Apbb2', 'Bcl2l1', 'Btg2', 'Chmp3', 'Grb14', 'Hsp90ab1', 'Hspa8', 'Igf1r', 'Irf1', 'Junb', 'Lef1', 'Mecom','Pdgfb', 'Plcb1', 'Sh3glb1', 'Tgfb1']
[N. OF USED GENES] 17
[Total number of cells]: 9730
[Number of cells used for training]: 8076
[Number of cells used for validation]: 1654
at least How many cycle genes should be calculated is reasonable?

**Comment by andreariba** [comment]
Your numbers appears very low, but the important thing is that the few you have are good genes. Check the output for the single genes with --hotelling option. From output figures you can have an idea of how good the fit is.
