### ISSUE TITLE
Appreciation for DeepCycle

### ISSUE THREAD

**Issue by FanliChong** [andreariba/DeepCycle#19]
Hello,

I just wanted to express my appreciation for your work on DeepCycle. I am currently in the process of using it for my single-cell sequencing data, and I find it to be a very valuable tool.

I am still learning how to use it and I am actively trying to get it to work with my data. I appreciate the effort you have put into developing this tool and making it available to the community.

Thank you for your great work!

Best regards,
FanliChong

**Comment by andreariba** [comment]
Hi Fanli,
Thanks a lot! Beware that DeepCycle will work only with deep sequenced datasets and if you're looking specifically into cycling cells.
If you need help let me know. 
Best,
Andrea

**Comment by FanliChong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Dear Andrea,
        
    
Thank you for your quick response and for the information about the requirements for using DeepCycle. I have checked my single-cell RNA sequencing data, and it was sequenced to a median depth of 5367 unique molecular identifiers (UMIs) per cell, with a median of 1569 genes detected per cell. I believe this should meet the requirement of "deep sequenced datasets".

Before encountering DeepCycle, I had tried many machine learning models for my research. However, none of them seemed to be quite right for studying cell cycle states. Discovering DeepCycle has given me hope and I am very excited about the potential it has for my research.

I am looking forward to using DeepCycle for my research. If I encounter any issues or have any questions, I will definitely reach out. Thank you again for your help and for your work on this valuable tool.
Best regards,
Fanli Chong
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Andrea ***@***.***>
            
        
      
      
        
         Date 
        
        
        7/7/2023 14:56
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [andreariba/DeepCycle] Appreciation for DeepCycle (Issue #19)
        
      
    
  
  
Hi Fanli,
Thanks a lot! Beware that DeepCycle will work only with deep sequenced datasets and if you're looking specifically into cycling cells.
If you need help let me know.
Best,
Andrea

**Comment by andreariba** [comment]
actually I have to say your dataset is quite shallow compared to any dataset I tested in the paper, not sure it will be enough.
Anyway the best of luck trying DeepCycle :)

**Comment by FanliChong** [comment]
Thank you, Andrea, for your honest feedback. I understand the limitations of my dataset. However, I still want to give DeepCycle a try as it seems to be a promising tool for my research. I appreciate your good wishes and will keep you updated on my progress. Thanks again for your support and for developing such a valuable tool:)

**Comment by FanliChong** [comment]
Dear Andrea,

I have a couple of questions that I hope you could help me with:

1.Could you share how DeepCycle uses quiescence markers to cluster cells in the quiescent state? Can these markers be numerous?

2.In my experiments, I have treated the cell type I am studying to a quiescent state and then performed mRNA-seq omics sequencing. Can these results help me identify whether these quiescence markers are specifically expressed in the cell type I am studying? Alternatively, can I directly use my omics sequencing results to perform binary classification through a machine model, which can then be used in new single-cell data? Or do you have any other suggestions?

I appreciate your time and look forward to your response.

Best regards

**Comment by andreariba** [comment]
1. DeepCycle alone will not identify the quiescent cells, we identified the subpopulation of quiescent cells by clustering and identified the not proliferating by marker genes that you can find in the paper.
 
2. I'm not sure I understand your question, but if your population is quiescent for sure DeepCycle won't work.  Assuming you're not looking at a multiple overlapping processes different from proliferation, if you have multiple subpopulations you can hope that by clustering you can split the proliferative vs non proliferative cells as we did in the paper.

**Comment by FanliChong** [comment]
Dear Andrea,

Thank you for your detailed explanation. It helps me understand the capabilities and limitations of DeepCycle better. I understand now that DeepCycle won't work if my cell population is definitely in the quiescent phase. I will consider your advice about identifying proliferative and non-proliferative cells through clustering if I have multiple subpopulations.

I appreciate your time and assistance. Your work on DeepCycle is truly inspiring.

Best regards
