### ISSUE TITLE
plot_training

### ISSUE THREAD

**Issue by tcloaken** [andreariba/DeepCycle#2]
Had an error in 'DeepCycle.py' lines 435 and 436 where the 'val_kullback_leibler_divergence' nor the 'kullback_leibler_divergence' is not in the dict. I replaced with 'val_kl_divergence' and 'kl_divergence' respectively and then it ran successfully.

**Comment by andreariba** [comment]
You are not the first one having this error, it depends on the version of tensorflow. I'll try to fix it as soon as possible

**Comment by andreariba** [comment]
I removed the kullback leibler divergence from the plotting function, now it should work without this issue
